image: archlinux
packages:
  - rust
  - xorg-server
sources:
  - https://git.sr.ht/~paulcacheux/GameboyEmulator

tasks:
  - build: |
      cd GameboyEmulator
      cargo build --release

  - test: |
      cd GameboyEmulator
      cargo test -p gbemu

artifacts:
  - GameboyEmulator/target/release/gameboy_emulator