[package]
name = "gbemu"
version = "0.1.0"
authors = ["Paul Cacheux <paulcacheux@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4.21"
bitflags = "2.5.0"

[dev-dependencies.image]
default-features = false
features = ["png"]
version = "0.25.1"
