on: push

name: Lint

jobs:
  check:
    name: Lint and test emulator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Cache rust artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Run clippy
        run: |
          cargo clippy -- -D warnings

      - name: Run tests
        run: |
          cargo test